server:
  port: 8080


---
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-cd5sarhi.sql.tencentcdb.com:62910/springboot?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: siit2018!
#    username: ${AUTH_DB_PWD:simu}
#    password: ${AUTH_DB_USER:simu123}
#    type: com.zaxxer.hikari.HikariDataSource
#    schema[0]: classpath:/init.sql
#    initialize: true

logging:
  level:
    com.blueskykong.mybatis.dao: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG

---
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

